### ISSUE TITLE
 cannot take address of bit-field with newest cista

### ISSUE THREAD

**Issue by westfly** [felixguendling/cpp-serialization-benchmark#2]
when build with cista 0.7, the compile make an error 
```cannot take address of bit-field```
SO I redefine the code
```
 struct slim_graph {
   using string_t = cista::offset::string;
 
   struct edge {
-    uint32_t from_ : 11;
-    uint32_t to_ : 11;
-    uint32_t weight_ : 10;
+    uint32_t from_;
+    uint32_t to_;
+    uint32_t weight_;
   };
```

so  pls update the benchmark to the newest .

**Comment by felixguendling** [comment]
Updated: https://github.com/felixguendling/cpp-serialization-benchmark/commit/b3c46a13f9d5ad23915d0df22c47a1b4c9c17fff
